#include <iostream>
#include <sstream>
#include <fstream>
#include <chrono>
#include <vector>
#include <list>
#include <unordered_set>
#include <set>
#include <map>
#include <algorithm>
#include <string>

using namespace std;

class GeomVector
{
public:
    double x, y, z;
    GeomVector(double x, double y, double z)
    {
        this->x = x;
        this->y = y;
        this->z = z;
    };
};

/*
class STL_Reader{

};*/

vector<GeomVector> readStlFile(string inputFile)
{   
    vector<GeomVector> coordinates;

    int index = 0;
    ifstream ifs(inputFile, ios::in);
    if (ifs.good())
    {
        string line;
        string vertex;

        double x, y, z;

        while (getline(ifs, line))
        {
            stringstream ss;
            ss << line;
            ss >> vertex;
            if (vertex == "vertex")
            {
                ss >> x;
                ss >> y;
                ss >> z;
                index++;
                GeomVector g(x, y, z);
                // string coords =  to_string(x) + " " + to_string(y) + " " + to_string(z) + " ";
                coordinates.push_back(g);
            }
            else
                continue;
        }
        return coordinates;
    }
}

void printVertices(vector<GeomVector> vertices)
{
    for (auto point : vertices)
    {
        cout << point.x << " ";
        cout << point.y << " ";
        cout << point.z << endl;
    }
};

map<string, int> uniqueVertices(vector<GeomVector> vertices)
{
    int index = 0;
    map<string, int> uniqueCoords;
    for (auto ver : vertices)
    {
        string coords = to_string(ver.x) + " " + to_string(ver.y) + " " + to_string(ver.z) + " ";
        if (uniqueCoords.find(coords) == uniqueCoords.end())
        {
            uniqueCoords.insert({coords, ++index});
        }
    }
    return uniqueCoords;
};

void printUniqueVertices(map<string, int> printUniVertices)
{
    for (auto i : printUniVertices)
    {
        cout << "v " << i.first << endl;
    }
};

void facesPrint(map<string, int> printUniVertices, vector<GeomVector> vertices)
{
    int c = 0;
    for (auto ver : vertices)
    {
        if (c % 3 == 0)
            cout << "f ";
        string coords = to_string(ver.x) + " " + to_string(ver.y) + " " + to_string(ver.z) + " ";
        cout << " " << printUniVertices.at(coords);
        c++;
        if (c % 3 == 0)
            cout << endl;
    }
}

int main()
{

    auto t0 = chrono::system_clock::now();

    /*FILE READING*/
    string inputFile = "cube_ASCII.stl";
    // string inputFile = "humanoid.stl";
    string outputFile = "cube_ASCII.obj";

    vector<GeomVector> vertices = readStlFile(inputFile);
    // cout<<"Print All Vertices : "<<endl;
    // printVertices(vertices);
    // cout<<"Number of All Vertices : "<< vertices.size() << endl;
    cout << endl;

    cout << "Number of triangles : " << vertices.size() / 3 << endl;
    map<string, int> uniquePoints = uniqueVertices(vertices);
    cout << "Count of Unique Vertices : " << uniquePoints.size() << endl;
    //cout << "Print Unique Vertices : " << endl;
    //printUniqueVertices(uniquePoints);
    cout << endl;

    auto t1 = chrono::system_clock::now();
    auto elapsed = chrono::duration_cast<chrono::milliseconds>(t1 - t0);
    std::cout << "STL file is Read in Duration: " << elapsed.count() << " ms" << std::endl;

    /*OBJ FILE*/
    cout << "writing OBJ-File" << std::endl;
    ofstream fileOBJ(outputFile.c_str(), ios::out);
    fileOBJ << "Generated by Visualization toolkit" << endl;
    fileOBJ << outputFile << endl;
    fileOBJ << endl;
    fileOBJ << "mtlib cube.mtl" << endl;

    map<string, int> OBJVertex = uniqueVertices(vertices);
    for (auto ind : OBJVertex)
    {
        fileOBJ << "v " << ind.first << endl;
    }
    fileOBJ << endl;

    auto t2 = chrono::system_clock::now();
    elapsed = chrono::duration_cast<chrono::milliseconds>(t2 - t1);
    cout << "Unique Vertex is printed in OBJ File in : " << elapsed.count() << " ms" << std::endl;
    fileOBJ << "usemtl cube" << endl;

    /*Faces Count and writing into obj file*/
    vector<GeomVector> OBJAllVertices = readStlFile(inputFile);
    unsigned count = 0;
    for (auto ver : OBJAllVertices)
    {
        if (count % 3 == 0)
            fileOBJ << "f ";
        string coords = to_string(ver.x) + " " + to_string(ver.y) + " " + to_string(ver.z) + " ";
        fileOBJ << " " << OBJVertex.at(coords);
        count++;
        if (count % 3 == 0)
            fileOBJ << endl;
    }

    auto t3 = chrono::system_clock::now();
    elapsed = chrono::duration_cast<chrono::milliseconds>(t3 - t0);
    cout << "OBJ file written in " << elapsed.count() << " ms." << std::endl;
    
    return 0;
}